apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: productcatalog-abort-25
  namespace: default
spec:
  hosts:
  - productcatalogservice.default.svc.cluster.local
  http:
  - fault:
      abort:
        httpStatus: 503
        percentage: { value: 25 }
    route:
    - destination:
        host: productcatalogservice.default.svc.cluster.local