apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: recommendation-delay
  namespace: default
spec:
  hosts:
  - recommendationservice.default.svc.cluster.local
  http:
  - fault:
      delay:
        fixedDelay: 2s        # atraso
        percentage: { value: 100 }
    route:
    - destination:
        host: recommendationservice.default.svc.cluster.local